import type { SectionConfig } from '@/types'

export const sections: SectionConfig[] = [
  {
    key: 'living_room',
    label: 'Living Room',
    description: 'Take 2-3 photos of the living room.',
    minPhotos: 2,
    maxPhotos: 10,
    required: true,
  },
  {
    key: 'kitchen',
    label: 'Kitchen',
    description: 'Take 2-3 photos of the kitchen.',
    minPhotos: 2,
    maxPhotos: 10,
    required: true,
  },
  {
    key: 'appliances',
    label: 'Appliances',
    description: 'Photos of the stove, refrigerator, dishwasher, washer, and dryer.',
    minPhotos: 1,
    maxPhotos: 10,
    required: true,
  },
  {
    key: 'under_kitchen_sink',
    label: 'Under Kitchen Sink',
    description: 'Open the cabinet under the kitchen sink and take a photo of the interior.',
    minPhotos: 1,
    maxPhotos: 5,
    required: true,
  },
  {
    key: 'primary_bedroom',
    label: 'Primary Bedroom',
    description: 'Take 2-3 photos of the primary bedroom.',
    minPhotos: 2,
    maxPhotos: 10,
    required: true,
  },
  {
    key: 'bedroom_2',
    label: 'Bedroom 2',
    description: 'Take 2-3 photos of bedroom 2.',
    minPhotos: 2,
    maxPhotos: 10,
    required: true,
  },
  {
    key: 'bedroom_3',
    label: 'Bedroom 3',
    description: 'Take 2-3 photos of bedroom 3. Skip if not applicable.',
    minPhotos: 0,
    maxPhotos: 10,
    required: false,
  },
  {
    key: 'bedroom_4',
    label: 'Bedroom 4',
    description: 'Take 2-3 photos of bedroom 4. Skip if not applicable.',
    minPhotos: 0,
    maxPhotos: 10,
    required: false,
  },
  {
    key: 'primary_bathroom',
    label: 'Primary Bathroom',
    description: 'Take 2-3 photos of the primary bathroom.',
    minPhotos: 2,
    maxPhotos: 10,
    required: true,
  },
  {
    key: 'second_bathroom',
    label: 'Second Bathroom',
    description: 'Take 2-3 photos of the second bathroom.',
    minPhotos: 2,
    maxPhotos: 10,
    required: true,
  },
  {
    key: 'third_bathroom',
    label: 'Third Bathroom',
    description: 'Take 2-3 photos of the third bathroom.',
    minPhotos: 2,
    maxPhotos: 10,
    required: true,
  },
  {
    key: 'under_bathroom_sinks',
    label: 'Under Bathroom Sink(s)',
    description: 'Open the cabinet under each bathroom sink and take a photo of the interior.',
    minPhotos: 1,
    maxPhotos: 10,
    required: true,
  },
  {
    key: 'utility_room',
    label: 'Utility Room',
    description: 'Photos of the utility room; include washer and dryer.',
    minPhotos: 1,
    maxPhotos: 5,
    required: true,
  },
  {
    key: 'hvac_filter',
    label: 'HVAC Filter',
    description: 'Take a photo of the HVAC / air filter.',
    minPhotos: 1,
    maxPhotos: 5,
    required: true,
  },
  {
    key: 'exterior_front',
    label: 'Exterior – Front',
    description: 'Take a photo of the front of the property.',
    minPhotos: 1,
    maxPhotos: 5,
    required: true,
  },
  {
    key: 'exterior_rear',
    label: 'Exterior – Rear',
    description: 'Take a photo of the rear of the property.',
    minPhotos: 1,
    maxPhotos: 5,
    required: true,
  },
  {
    key: 'exterior_left',
    label: 'Exterior – Left Side',
    description: 'Take a photo of the left side of the property.',
    minPhotos: 1,
    maxPhotos: 5,
    required: true,
  },
  {
    key: 'exterior_right',
    label: 'Exterior – Right Side',
    description: 'Take a photo of the right side of the property.',
    minPhotos: 1,
    maxPhotos: 5,
    required: true,
  },
  {
    key: 'porch_garage_misc',
    label: 'Porch, Garage, Miscellaneous',
    description: 'Photos of porches, garages, and any other relevant exterior areas.',
    minPhotos: 1,
    maxPhotos: 10,
    required: true,
  },
]
